INSERT INTO books (id, title, author, description, isbn, pages, publisher, published)
VALUES (RANDOM_UUID(),
        'How to Win Friends & Influence People',
        'Dale Carnegie',
        'How to Win Friends and Influence People is just as useful today as it was when it was first published, because Dale Carnegie had an understanding of human nature that will never be outdated. Financial success, Carnegie believed, is due 15 percent to professional knowledge and 85 percent to "the ability to express ideas, to assume leadership, and to arouse enthusiasm among people." He teaches these skills through underlying principles of dealing with people so that they feel important and appreciated. He also emphasizes fundamental techniques for handling people without making them feel manipulated.',
        '978-8183227896',
        299,
        'Amaryllis',
        '2017-01-02'),

        (RANDOM_UUID(),
        'Clean Code: A Handbook of Agile Software Craftsmanship',
        'Robert C. Martin',
        'Noted software expert Robert C. Martin presents a revolutionary paradigm with "Clean Code: A Handbook of Agile Software Craftsmanship." Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code "on the fly" into a book that will instill within you the values of a software craftsman and make you a better programmer--but only if you work at it.',
        '978-0132350884',
        464,
        'Prentice Hall',
        '2008-08-11'),

        (RANDOM_UUID(),
        'Code Complete: A Practical Handbook of Software Construction, Second Edition',
        'Steve McConnell',
        'Widely considered one of the best practical guides to programming, Steve McConnell’s original CODE COMPLETE has been helping developers write better software for more than a decade. Now this classic book has been fully updated and revised with leading-edge practices—and hundreds of new code samples—illustrating the art and science of software construction.',
        '978-0735619678',
        960,
        'Microsoft Press',
        '2004-06-19'),

        (RANDOM_UUID(),
        'Effective Java (2nd Edition)',
        'Joshua Bloch',
        'Effective Java, Second Edition, brings together seventy-eight indispensable programmer’s rules of thumb: working, best-practice solutions for the programming challenges you encounter every day.',
        '978-0321356680',
        346,
        'Addison-Wesley',
        '2008-05-28'),

        (RANDOM_UUID(),
        'The C Programming Language, Second Edition',
        'Dennis M. Ritchie',
        'The authors present the complete guide to ANSI standard C language programming. Written by the developers of C, this new version helps readers keep up with the finalized ANSI standard for C while showing how to take advantage of C''s rich set of operators, economy of expression, improved control flow, and data structures.',
        '978-0131103627',
        272,
        'Prentice Hall',
        '1988-04-01');